name: Portfolio Deployment in GCS

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure GCP Credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_acount_key: ${{ secrets.GCP_SECRET_SA_KEY }}
        region: us-central1
    - name: Deploy to GCS
      run: |
         gsutil -m cp -r ./* gs://githubaction/

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://tws-portfolio --delete
